ICU 77.1: U_HEADER_ONLY_NAMESPACE::USetRangeIterator Class Reference
U_HEADER_ONLY_NAMESPACE::USetRangeIterator Class Reference
Iterator returned by USetRanges.
#include <uset.h>
Public Member Functions
USetRangeIterator (const USetRangeIterator &other)=default
bool operator== (const USetRangeIterator &other) const
bool operator!= (const USetRangeIterator &other) const
CodePointRange operator* () const
USetRangeIterator & operator++ ()
Pre-increment.
USetRangeIterator operator++ (int)
Post-increment.
Friends
class USetRanges
Detailed Description
Iterator returned by USetRanges.
Draft:
This API may be changed in the future versions and was introduced in ICU 76
Definition at line 1525 of file uset.h.
Constructor & Destructor Documentation
USetRangeIterator()
U_HEADER_ONLY_NAMESPACE::USetRangeIterator::USetRangeIterator (const USetRangeIterator & other) default
Draft:
This API may be changed in the future versions and was introduced in ICU 76
Member Function Documentation
operator!=()
bool U_HEADER_ONLY_NAMESPACE::USetRangeIterator::operator!= (const USetRangeIterator & other) const inline
Draft:
This API may be changed in the future versions and was introduced in ICU 76
Definition at line 1540 of file uset.h.
References operator==().
operator*()
CodePointRange U_HEADER_ONLY_NAMESPACE::USetRangeIterator::operator* () const inline
Draft:
This API may be changed in the future versions and was introduced in ICU 76
Definition at line 1543 of file uset.h.
References U_SENTINEL, U_SUCCESS, U_ZERO_ERROR, and uset_getItem().
operator++() [1/2]
USetRangeIterator& U_HEADER_ONLY_NAMESPACE::USetRangeIterator::operator++ () inline
Pre-increment.
Draft:
This API may be changed in the future versions and was introduced in ICU 76
Definition at line 1559 of file uset.h.
operator++() [2/2]
USetRangeIterator U_HEADER_ONLY_NAMESPACE::USetRangeIterator::operator++ (int) inline
Post-increment.
Draft:
This API may be changed in the future versions and was introduced in ICU 76
Definition at line 1568 of file uset.h.
operator==()
bool U_HEADER_ONLY_NAMESPACE::USetRangeIterator::operator== (const USetRangeIterator & other) const inline
Draft:
This API may be changed in the future versions and was introduced in ICU 76
Definition at line 1531 of file uset.h.
Referenced by operator!=().
The documentation for this class was generated from the following file:
common/unicode/uset.h