ICU 65.1: icu Namespace Reference
icu Namespace Reference
File coll.h.
Data Structures
class AlphabeticIndex
AlphabeticIndex supports the creation of a UI index appropriate for a given language.
class AnnualTimeZoneRule
AnnualTimeZoneRule is a class used for representing a time zone rule which takes effect annually.
class Appendable
Base class for objects to which Unicode characters and strings can be appended.
class BasicTimeZone
BasicTimeZone is an abstract class extending TimeZone.
class BreakIterator
The BreakIterator class implements methods for finding the location of boundaries in text.
class ByteSink
A ByteSink can be filled with bytes.
class BytesTrie
Light-weight, non-const reader class for a BytesTrie.
class BytesTrieBuilder
Builder class for BytesTrie.
class Calendar
Calendar is an abstract base class for converting between a UDate object and a set of integer fields such as YEAR, MONTH, DAY, HOUR, and so on.
class CanonicalIterator
This class allows one to iterate through all the strings that are canonically equivalent to a given string.
class CaseMap
Low-level C++ case mapping functions.
class Char16Ptr
char16_t * wrapper with implicit conversion from distinct but bit-compatible pointer types.
class CharacterIterator
Abstract class that defines an API for iteration on text objects.
class CheckedArrayByteSink
Implementation of ByteSink that writes to a flat byte array, with bounds-checking: This sink will not write more than capacity bytes to outbuf.
class ChoiceFormat
ChoiceFormat converts between ranges of numeric values and strings for those ranges.
class CollationElementIterator
The CollationElementIterator class is used as an iterator to walk through each character of an international string.
class CollationKey
Collation keys are generated by the Collator class.
class Collator
The Collator class performs locale-sensitive string comparison.
class CollatorFactory
A factory, used with registerFactory, the creates multiple collators and provides display names for them.
class CompactDecimalFormat
IMPORTANT: New users are strongly encouraged to see if numberformatter.h fits their use case.
class ConstChar16Ptr
const char16_t * wrapper with implicit conversion from distinct but bit-compatible pointer types.
class ConstrainedFieldPosition
Represents a span of a string containing a given field.
class CurrencyAmount
A currency together with a numeric amount, such as 200 USD.
class CurrencyPluralInfo
This class represents the information needed by DecimalFormat to format currency plural, such as "3.00 US dollars" or "1.00 US dollar".
class CurrencyUnit
A unit of currency, such as USD (U.S.
class DateFormat
DateFormat is an abstract class for a family of classes that convert dates and times from their internal representations to textual form and back again in a language-independent manner.
class DateFormatSymbols
DateFormatSymbols is a public class for encapsulating localizable date-time formatting data – including timezone data.
class DateInterval
This class represents a date interval.
class DateIntervalFormat
DateIntervalFormat is a class for formatting and parsing date intervals in a language-independent manner.
class DateIntervalInfo
DateIntervalInfo is a public class for encapsulating localizable date time interval patterns.
class DateTimePatternGenerator
This class provides flexible generation of date format patterns, like "yy-MM-dd".
class DateTimeRule
DateTimeRule is a class representing a time in a year by a rule specified by month, day of month, day of week and time in the day.
class DecimalFormat
IMPORTANT: New users are strongly encouraged to see if numberformatter.h fits their use case.
class DecimalFormatSymbols
This class represents the set of symbols needed by DecimalFormat to format numbers.
class Edits
Records lengths of string edits but not replacement text.
class ErrorCode
Wrapper class for UErrorCode, with conversion operators for direct use in ICU C and C++ APIs.
class FieldPosition
FieldPosition is a simple class used by Format and its subclasses to identify fields in formatted output.
class FieldPositionIterator
FieldPositionIterator returns the field ids and their start/limit positions generated by a call to Format::format.
class FilteredBreakIteratorBuilder
The BreakIteratorFilter is used to modify the behavior of a BreakIterator by constructing a new BreakIterator which suppresses certain segment boundaries.
class FilteredNormalizer2
Normalization filtered by a UnicodeSet.
class FontRuns
The FontRuns class associates pointers to LEFontInstance objects with runs of text.
class Format
Base class for all formats.
class Formattable
Formattable objects can be passed to the Format class or its subclasses for formatting.
class FormattedDateInterval
An immutable class containing the result of a date interval formatting operation.
class FormattedList
An immutable class containing the result of a list formatting operation.
class FormattedRelativeDateTime
An immutable class containing the result of a relative datetime formatting operation.
class FormattedValue
An abstract formatted value: a string with associated field attributes.
class ForwardCharacterIterator
Abstract class that defines an API for forward-only iteration on text objects.
class GenderInfo
GenderInfo computes the gender of a list as a whole given the gender of each element.
class GregorianCalendar
Concrete class which provides the standard calendar used by most of the world.
class IDNA
Abstract base class for IDNA processing.
class IDNAInfo
Output container for IDNA processing errors.
class InitialTimeZoneRule
InitialTimeZoneRule represents a time zone rule representing a time zone effective from the beginning and has no actual start times.
class ListFormatter
An immutable class for formatting a list, using data from CLDR (or supplied separately).
class LocalArray
"Smart pointer" class, deletes objects via the C++ array delete[] operator.
class Locale
A Locale object represents a specific geographical, political, or cultural region.
class LocaleBuilder
LocaleBuilder is used to build instances of Locale from values configured by the setters.
class LocaleDisplayNames
Returns display names of Locales and components of Locales.
class LocaleMatcher
Immutable class that picks the best match between a user's desired locales and an application's supported locales.
class LocaleRuns
The LocaleRuns class associates pointers to Locale objects with runs of text.
class LocalPointer
"Smart pointer" class, deletes objects via the standard C++ delete operator.
class LocalPointerBase
"Smart pointer" base class; do not use directly: use LocalPointer etc.
class Measure
An amount of a specified unit, consisting of a number and a Unit.
class MeasureFormat
class MeasureUnit
A unit such as length, mass, volume, currency, etc.
class MessageFormat
class MessagePattern
Parses and represents ICU MessageFormat patterns.
class Normalizer
Old Unicode normalization API.
class Normalizer2
Unicode normalization functionality for standard Unicode normalization or for using custom mapping tables.
class NoUnit
Dimensionless unit for percent and permille.
class NumberFormat
class NumberFormatFactory
A NumberFormatFactory is used to register new number formats.
class NumberingSystem
Defines numbering systems.
class ParagraphLayout
ParagraphLayout.
class ParsePosition
ParsePosition is a simple class used by Format and its subclasses to keep track of the current position during parsing.
class PluralFormat
class PluralRules
Defines rules for mapping non-negative numeric values onto a small set of keywords.
class RegexMatcher
class RegexMatcher bundles together a regular expression pattern and input text to which the expression can be applied.
class RegexPattern
Class RegexPattern represents a compiled regular expression.
class Region
Region is the class representing a Unicode Region Code, also known as a Unicode Region Subtag, which is defined based upon the BCP 47 standard.
class RelativeDateTimeFormatter
Formats simple relative dates.
class Replaceable
Replaceable is an abstract base class representing a string of characters that supports the replacement of a range of itself with a new string of characters.
class ResourceBundle
A class representing a collection of resource information pertaining to a given locale.
class RuleBasedBreakIterator
A subclass of BreakIterator whose behavior is specified using a list of rules.
class RuleBasedCollator
The RuleBasedCollator class provides the implementation of Collator, using data-driven tables.
class RuleBasedNumberFormat
The RuleBasedNumberFormat class formats numbers according to a set of rules.
class RuleBasedTimeZone
a BasicTimeZone subclass implemented in terms of InitialTimeZoneRule and TimeZoneRule instances
class RunArray
The RunArray class is a base class for building classes which represent data that is associated with runs of text.
class ScientificNumberFormatter
A formatter that formats numbers in user-friendly scientific notation.
class SearchIterator
SearchIterator is an abstract base class that provides methods to search for a pattern within a text string.
class SelectFormat
class SimpleDateFormat
SimpleDateFormat is a concrete class for formatting and parsing dates in a language-independent manner.
class SimpleFormatter
Formats simple patterns like "{1} was born in {0}".
class SimpleNumberFormatFactory
A NumberFormatFactory that supports a single locale.
class SimpleTimeZone
SimpleTimeZone is a concrete subclass of TimeZone that represents a time zone for use with a Gregorian calendar.
class StringByteSink
Implementation of ByteSink that writes to a "string".
class StringCharacterIterator
A concrete subclass of CharacterIterator that iterates over the characters (code units or code points) in a UnicodeString.
class StringEnumeration
Base class for 'pure' C++ implementations of uenum api.
class StringPiece
A string-like object that points to a sized piece of memory.
class StringSearch
StringSearch is a SearchIterator that provides language-sensitive text searching based on the comparison rules defined in a RuleBasedCollator object.
class SymbolTable
An interface that defines both lookup protocol and parsing of symbolic names.
class TimeArrayTimeZoneRule
TimeArrayTimeZoneRule represents a time zone rule whose start times are defined by an array of milliseconds since the standard base time.
class TimeUnit
Measurement unit for time units.
class TimeUnitAmount
Express a duration as a time unit and number.
class TimeUnitFormat
Format or parse a TimeUnitAmount, using plural rules for the units where available.
class TimeZone
TimeZone represents a time zone offset, and also figures out daylight savings.
class TimeZoneFormat
TimeZoneFormat supports time zone display name formatting and parsing.
class TimeZoneNames
TimeZoneNames is an abstract class representing the time zone display name data model defined by UTS#35 Unicode Locale Data Markup Language (LDML).
class TimeZoneRule
TimeZoneRule is a class representing a rule for time zone.
class TimeZoneTransition
TimeZoneTransition is a class representing a time zone transition.
class Transliterator
Transliterator is an abstract class that transliterates text from one format to another.
class UCharCharacterIterator
A concrete subclass of CharacterIterator that iterates over the characters (code units or code points) in a char16_t array.
class UCharsTrie
Light-weight, non-const reader class for a UCharsTrie.
class UCharsTrieBuilder
Builder class for UCharsTrie.
class UMemory
UMemory is the common ICU base class.
class UnicodeFilter
UnicodeFilter defines a protocol for selecting a subset of the full range (U+0000 to U+10FFFF) of Unicode characters.
class UnicodeFunctor
UnicodeFunctor is an abstract base class for objects that perform match and/or replace operations on Unicode strings.
class UnicodeMatcher
UnicodeMatcher defines a protocol for objects that can match a range of characters in a Replaceable string.
class UnicodeReplacer
UnicodeReplacer defines a protocol for objects that replace a range of characters in a Replaceable string with output text.
class UnicodeSet
A mutable set of Unicode characters and multicharacter strings.
class UnicodeSetIterator
UnicodeSetIterator iterates over the contents of a UnicodeSet.
class UnicodeString
UnicodeString is a string class that stores Unicode characters directly and provides similar functionality as the Java String and StringBuffer/StringBuilder classes.
class UnicodeStringAppendable
An Appendable implementation which writes to a UnicodeString.
class UObject
UObject is the common ICU "boilerplate" class.
class ValueRuns
The ValueRuns class associates integer values with runs of text.
class VTimeZone
VTimeZone is a class implementing RFC2445 VTIMEZONE.
Typedefs
typedef RuleBasedBreakIterator DictionaryBasedBreakIterator
An obsolete subclass of RuleBasedBreakIterator.
typedef int32_t UFieldResolutionTable[12][8]
Enumerations
enum UMatchDegree { U_MISMATCH, U_PARTIAL_MATCH, U_MATCH }
Constants returned by UnicodeMatcher::matches() indicating the degree of match.
enum URBNFRuleSetTag {
URBNF_SPELLOUT, URBNF_ORDINAL, URBNF_DURATION, URBNF_NUMBERING_SYSTEM,
URBNF_COUNT
}
Tags for the predefined rulesets.
Functions
const UChar * toUCharPtr (const char16_t *p)
Converts from const char16_t * to const UChar *.
UChar * toUCharPtr (char16_t *p)
Converts from char16_t * to UChar *.
const OldUChar * toOldUCharPtr (const char16_t *p)
Converts from const char16_t * to const OldUChar *.
OldUChar * toOldUCharPtr (char16_t *p)
Converts from char16_t * to OldUChar *.
void locale_available_init ()
U_EXPORT UBool operator== (const StringPiece &x, const StringPiece &y)
Global operator == for StringPiece.
UBool operator!= (const StringPiece &x, const StringPiece &y)
Global operator != for StringPiece.
U_COMMON_API UnicodeString operator+ (const UnicodeString &s1, const UnicodeString &s2)
Create a new UnicodeString with the concatenation of two others.
UnicodeString ures_getUnicodeString (const UResourceBundle *resB, UErrorCode *status)
Returns the string value from a string resource bundle.
UnicodeString ures_getNextUnicodeString (UResourceBundle *resB, const char **key, UErrorCode *status)
Returns the next string in a resource, or an empty string if there are no more resources to iterate over.
UnicodeString ures_getUnicodeStringByIndex (const UResourceBundle *resB, int32_t indexS, UErrorCode *status)
Returns the string in a given resource array or table at the specified index.
UnicodeString ures_getUnicodeStringByKey (const UResourceBundle *resB, const char *key, UErrorCode *status)
Returns a string in a resource that has a given key.
void GenderInfo_initCache (UErrorCode &status)
U_IO_API std::ostream & operator<< (std::ostream &stream, const UnicodeString &s)
Write the contents of a UnicodeString to a C++ ostream.
U_IO_API std::istream & operator>> (std::istream &stream, UnicodeString &s)
Write the contents from a C++ istream to a UnicodeString.
Variables
constexpr const size_t kInternalNumSysNameCapacity = 8
Size of a numbering system name.
Detailed Description
File coll.h.
File tblcoll.h.
Created by: Helena Shih
Modification History:
Date Name Description 02/5/97 aliu Modified createDefault to load collation data from binary files when possible. Added related methods createCollationFromFile, chopLocale, createPathName. 02/11/97 aliu Added members addToCache, findInCache, and fgCache. 02/12/97 aliu Modified to create objects from RuleBasedCollator cache. Moved cache out of Collation class. 02/13/97 aliu Moved several methods out of this class and into RuleBasedCollator, with modifications. Modified createDefault() to call new RuleBasedCollator(Locale&) constructor. General clean up and documentation. 02/20/97 helena Added clone, operator==, operator!=, operator=, copy constructor and getDynamicClassID. 03/25/97 helena Updated with platform independent data types. 05/06/97 helena Added memory allocation error detection. 06/20/97 helena Java class name change. 09/03/97 helena Added createCollationKeyValues(). 02/10/98 damiba Added compare() with length as parameter. 04/23/99 stephen Removed EDecompositionMode, merged with Normalizer::EMode. 11/02/99 helena Collator performance enhancements. Eliminates the UnicodeString construction and special case for NO_OP. 11/23/99 srl More performance enhancements. Inlining of critical accessors. 05/15/00 helena Added version information API. 01/29/01 synwee Modified into a C++ wrapper which calls C apis (ucol.h). 2012-2014 markus Rewritten in C++ again.
Created by: Helena Shih
Modification History:
Date Name Description 2/5/97 aliu Added streamIn and streamOut methods. Added constructor which reads RuleBasedCollator object from a binary file. Added writeToFile method which streams RuleBasedCollator out to a binary file. The streamIn and streamOut methods use istream and ostream objects in binary mode. 2/12/97 aliu Modified to use TableCollationData sub-object to hold invariant data. 2/13/97 aliu Moved several methods into this class from Collation. Added a private RuleBasedCollator(Locale&) constructor, to be used by Collator::createDefault(). General clean up. 2/20/97 helena Added clone, operator==, operator!=, operator=, and copy constructor and getDynamicClassID. 3/5/97 aliu Modified constructFromFile() to add parameter specifying whether or not binary loading is to be attempted. This is required for dynamic rule loading. 05/07/97 helena Added memory allocation error detection. 6/17/97 helena Added IDENTICAL strength for compare, changed getRules to use MergeCollation::getPattern. 6/20/97 helena Java class name change. 8/18/97 helena Added internal API documentation. 09/03/97 helena Added createCollationKeyValues(). 02/10/98 damiba Added compare with "length" parameter 08/05/98 erm Synched with 1.2 version of RuleBasedCollator.java 04/23/99 stephen Removed EDecompositionMode, merged with Normalizer::EMode 06/14/99 stephen Removed kResourceBundleSuffix 11/02/99 helena Collator performance enhancements. Eliminates the UnicodeString construction and special case for NO_OP. 11/23/99 srl More performance enhancements. Updates to NormalizerIterator internal state management. 12/15/99 aliu Update to support Thai collation. Move NormalizerIterator to implementation file. 01/29/01 synwee Modified into a C++ wrapper which calls C API (ucol.h) 2012-2014 markus Rewritten in C++ again.
Typedef Documentation
DictionaryBasedBreakIterator
typedef RuleBasedBreakIterator icu::DictionaryBasedBreakIterator
An obsolete subclass of RuleBasedBreakIterator.
Handling of dictionary- based break iteration has been folded into the base class. This class is deprecated as of ICU 3.6.
Deprecated:
ICU 3.6
Definition at line 38 of file dbbi.h.
UFieldResolutionTable
typedef int32_t icu::UFieldResolutionTable[12][8]
Internal:
Do not use.
This API is for internal use only.
Definition at line 48 of file calendar.h.
Enumeration Type Documentation
UMatchDegree
enum icu::UMatchDegree
Constants returned by UnicodeMatcher::matches() indicating the degree of match.
Stable:
ICU 2.4
Enumerator
U_MISMATCH
Constant returned by matches() indicating a mismatch between the text and this matcher.
The text contains a character which does not match, or the text does not contain all desired characters for a non-incremental match.
Stable:
ICU 2.4
U_PARTIAL_MATCH
Constant returned by matches() indicating a partial match between the text and this matcher.
This value is only returned for incremental match operations. All characters of the text match, but more characters are required for a complete match. Alternatively, for variable-length matchers, all characters of the text match, and if more characters were supplied at limit, they might also match.
Stable:
ICU 2.4
U_MATCH
Constant returned by matches() indicating a complete match between the text and this matcher.
For an incremental variable-length match, this value is returned if the given text matches, and it is known that additional characters would not alter the extent of the match.
Stable:
ICU 2.4
Definition at line 33 of file unimatch.h.
URBNFRuleSetTag
enum icu::URBNFRuleSetTag
Tags for the predefined rulesets.
Stable:
ICU 2.2
Enumerator
URBNF_COUNT
One more than the highest normal URBNFRuleSetTag value.
Deprecated:
ICU 58 The numeric value may change over time, see ICU ticket #12420.
Definition at line 56 of file rbnf.h.
Function Documentation
GenderInfo_initCache()
void icu::GenderInfo_initCache (UErrorCode & status)
Internal:
Do not use.
This API is for internal use only. Forward Declaration
locale_available_init()
void icu::locale_available_init ()
Internal:
Do not use.
This API is for internal use only.
Referenced by icu::Locale::ConvertingIterator< Iter, Conv >::next().
operator!=()
UBool icu::operator!= (const StringPiece & x, const StringPiece & y) inline
Global operator != for StringPiece.
Parameters
x The first StringPiece to compare.
y The second StringPiece to compare.
Returns
TRUE if the string data is not equal
Stable:
ICU 4.8
Definition at line 251 of file stringpiece.h.
Referenced by icu::FieldPosition::FieldPosition(), and icu::ParsePosition::ParsePosition().
operator+()
U_COMMON_API UnicodeString icu::operator+ (const UnicodeString & s1, const UnicodeString & s2)
Create a new UnicodeString with the concatenation of two others.
Parameters
s1 The first string to be copied to the new one.
s2 The second string to be copied to the new one, after s1.
Returns
UnicodeString(s1).append(s2)
Stable:
ICU 2.8
Referenced by icu::UnicodeString::UnicodeString().
operator<<()
U_IO_API std::ostream& icu::operator<< (std::ostream & stream, const UnicodeString & s)
Write the contents of a UnicodeString to a C++ ostream.
This functions writes the characters in a UnicodeString to an ostream. The UChars in the UnicodeString are converted to the char based ostream with the default converter.
Stable:
3.0
operator==()
U_EXPORT UBool icu::operator== (const StringPiece & x, const StringPiece & y)
Global operator == for StringPiece.
Parameters
x The first StringPiece to compare.
y The second StringPiece to compare.
Returns
TRUE if the string data is equal
Stable:
ICU 4.8
Referenced by icu::UCharsTrieBuilder::clear(), icu::MessagePattern::clearPatternAndSetApostropheMode(), icu::FieldPosition::FieldPosition(), icu::MessagePattern::Part::hasNumericValue(), icu::FieldPositionIterator::operator!=(), icu::CurrencyPluralInfo::operator!=(), icu::ParsePosition::operator!=(), icu::Format::operator!=(), icu::RegexPattern::operator!=(), icu::BreakIterator::operator!=(), icu::TimeZoneNames::operator!=(), icu::FieldPosition::operator!=(), icu::DateFormatSymbols::operator!=(), icu::Formattable::operator!=(), icu::DateIntervalInfo::operator!=(), icu::DecimalFormatSymbols::operator!=(), icu::SearchIterator::operator!=(), icu::Locale::operator!=(), icu::DateIntervalFormat::operator!=(), icu::TimeZone::operator!=(), icu::Calendar::operator!=(), icu::PluralRules::operator!=(), icu::UnicodeSet::operator!=(), icu::MessagePattern::operator!=(), icu::Normalizer::operator!=(), icu::MessagePattern::Part::operator!=(), icu::ParsePosition::ParsePosition(), icu::Calendar::setTime(), and icu::StringPiece::substr().
operator>>()
U_IO_API std::istream& icu::operator>> (std::istream & stream, UnicodeString & s)
Write the contents from a C++ istream to a UnicodeString.
The UChars in the UnicodeString are converted from the char based istream with the default converter.
Stable:
3.0
toOldUCharPtr() [1/2]
const OldUChar* icu::toOldUCharPtr (const char16_t * p) inline
Converts from const char16_t * to const OldUChar *.
Includes an aliasing barrier if available.
Parameters
p pointer
Returns
p as const OldUChar *
Stable:
ICU 59
Definition at line 288 of file char16ptr.h.
References U_ALIASING_BARRIER.
toOldUCharPtr() [2/2]
OldUChar* icu::toOldUCharPtr (char16_t * p) inline
Converts from char16_t * to OldUChar *.
Includes an aliasing barrier if available.
Parameters
p pointer
Returns
p as OldUChar *
Stable:
ICU 59
Definition at line 302 of file char16ptr.h.
References U_ALIASING_BARRIER.
toUCharPtr() [1/2]
const UChar* icu::toUCharPtr (const char16_t * p) inline
Converts from const char16_t * to const UChar *.
Includes an aliasing barrier if available.
Parameters
p pointer
Returns
p as const UChar *
Stable:
ICU 59
Definition at line 260 of file char16ptr.h.
References U_ALIASING_BARRIER.
Referenced by icu::Normalizer::compare(), icu::UnicodeString::endsWith(), and icu::UnicodeString::startsWith().
toUCharPtr() [2/2]
UChar* icu::toUCharPtr (char16_t * p) inline
Converts from char16_t * to UChar *.
Includes an aliasing barrier if available.
Parameters
p pointer
Returns
p as UChar *
Stable:
ICU 59
Definition at line 274 of file char16ptr.h.
References U_ALIASING_BARRIER.
ures_getNextUnicodeString()
UnicodeString icu::ures_getNextUnicodeString (UResourceBundle * resB, const char ** key, UErrorCode * status) inline
Returns the next string in a resource, or an empty string if there are no more resources to iterate over.
Use ures_getNextString() instead to distinguish between the end of the iteration and a real empty string value.
Parameters
resB a resource
key fill in for key associated with this string
status fills in the outgoing error code
Returns
The string value, or a bogus string if there is a failure UErrorCode.
Stable:
ICU 2.0
Definition at line 834 of file ures.h.
References icu::UnicodeString::setTo(), icu::UnicodeString::setToBogus(), TRUE, U_SUCCESS, and ures_getNextString().
ures_getUnicodeString()
UnicodeString icu::ures_getUnicodeString (const UResourceBundle * resB, UErrorCode * status) inline
Returns the string value from a string resource bundle.
Parameters
resB a resource, should have type URES_STRING
status fills in the outgoing error code could be U_MISSING_RESOURCE_ERROR if the key is not found could be a non-failing error e.g.: U_USING_FALLBACK_WARNING,U_USING_DEFAULT_WARNING
Returns
The string value, or a bogus string if there is a failure UErrorCode.
Stable:
ICU 2.0
Definition at line 809 of file ures.h.
References icu::UnicodeString::setTo(), icu::UnicodeString::setToBogus(), TRUE, U_SUCCESS, and ures_getString().
ures_getUnicodeStringByIndex()
UnicodeString icu::ures_getUnicodeStringByIndex (const UResourceBundle * resB, int32_t indexS, UErrorCode * status) inline
Returns the string in a given resource array or table at the specified index.
Parameters
resB a resource
indexS an index to the wanted string.
status fills in the outgoing error code
Returns
The string value, or a bogus string if there is a failure UErrorCode.
Stable:
ICU 2.0
Definition at line 856 of file ures.h.
References icu::UnicodeString::setTo(), icu::UnicodeString::setToBogus(), TRUE, U_SUCCESS, and ures_getStringByIndex().
ures_getUnicodeStringByKey()
UnicodeString icu::ures_getUnicodeStringByKey (const UResourceBundle * resB, const char * key, UErrorCode * status) inline
Returns a string in a resource that has a given key.
This procedure works only with table resources.
Parameters
resB a resource
key a key associated with the wanted string
status fills in the outgoing error code
Returns
The string value, or a bogus string if there is a failure UErrorCode.
Stable:
ICU 2.0
Definition at line 879 of file ures.h.
References icu::UnicodeString::setTo(), icu::UnicodeString::setToBogus(), TRUE, U_STABLE, U_SUCCESS, ures_getStringByKey(), and ures_openAvailableLocales().
Variable Documentation
kInternalNumSysNameCapacity
constexpr const size_t icu::kInternalNumSysNameCapacity = 8
Size of a numbering system name.
Internal:
Do not use. This API is for internal use only.
Definition at line 42 of file numsys.h.